[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "d4d8c7e62ee0ae40a494690c1a60b8fbb61526d9"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "0e693db038a435421c4c75b72067857c5e440535c73cbd2f185838679f656447"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.aarch64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9382c493b67bf9486900da306ab375b42e1b53de"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "3e718ad85081adcce145924916b67a8f9d007d48d423136c762aa72d89fec09d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.aarch64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2644086b9416aa1837513e0082c94c5333264c10"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "caab96ffad925875355a8f357931c825018705185be46f277a417999d8c2ea24"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.aarch64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "aarch64"
git-tree-sha1 = "90c82d985ead0fb44efd0836bf5ac868cfcc33f8"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "595739eb584bc97664c4b2c0678e3a764ea40c47c9836e2f30b88c2cdf42386d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.aarch64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "622452ee6b752a6a51033639acf0498809ddcc09"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "22fad0632d36d306c69d17fd81a6e37d09cd48e30aabdbdd6aca552c8f4a2d1e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72da7529988ff9054c5b888bd9f5a5923b2a513e"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "18878f0bfed7f4438cf829f1eca8c0a2322adfa65211fda59f95963052ce7aaa"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.armv6l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5d2987419312ce87f7b8c339961ccef2801a9d6"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "f23f82151efb46a7602b3d41092243572549e336001a6bf4a4f4b713186dfbe2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fdb255a5fba3b5f23755b9b75aa2f48f993bddc0"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "dffb6444488c9615e3e8f947ab7d1ecba844730b485471c24c68bb6693b473cb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1f7519da89531ca5b206082b8fdb40587679666"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "45aaa44854b1a15f5a309f49983d0a1530f99cd9b3f02150fadcd94ad100359f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.i686-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03e19b81354be8cbf9e830dbaea6b5cdac76e7e0"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "406304d58edb989956a13416fbc65e802b99dfbdd3c9753552134388c6a4004e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.i686-w64-mingw32-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2376b4205978d236190684afd2c3ee4918abc144"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "a5018d50c3f2e9139a84f944de5146e636811cf507850dd37bd191b7fcdb8667"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b75b2d11efca69e67a700994c71dd06fbd9e970"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "fca318109fc7ba54bf694f9a298fb2e620e5207895270cb2350ec7ce1019ecce"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.riscv64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "0f0403821463e9713d3996f198ec0ebc4640dae6"
os = "macos"

    [[LLVM_full_assert.download]]
    sha256 = "c7400c2ad83360f8b455726911477bc97aafcf86b827fe1be0226bfe175292b5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.x86_64-apple-darwin.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3af83e76157a254c339bc1eaadc2febc3ab49332"
libc = "glibc"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "dda6e5df35555fe630e316589c39f895e09dc496e2a45f9a6c8ecfef826167c7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.x86_64-linux-gnu-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be59354f17249359753b5961be9bd9e7dd71e52b"
libc = "musl"
os = "linux"

    [[LLVM_full_assert.download]]
    sha256 = "9eff6ea8a3952af8b6e25003fc1ecfee10ea12bf58ec68692f33ff1fc4f1cad1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.x86_64-linux-musl-cxx11.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
git-tree-sha1 = "75670f6d6c8dd9449773f024752a274c3cacab55"
os = "freebsd"

    [[LLVM_full_assert.download]]
    sha256 = "2ba60e494d0e6c2d3311d4d53afe020ef39416ef9f630977989fff06f88e0efc"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.x86_64-unknown-freebsd.tar.gz"
[[LLVM_full_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eac54207b3b16bb6cd4d93a5d24185de1e177253"
os = "windows"

    [[LLVM_full_assert.download]]
    sha256 = "75342133cd3900eeaa8ace213fda9d78996f0df2800622b2c64f41c3727389f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_full_assert_jll.jl/releases/download/LLVM_full_assert-v15.0.7+11/LLVM_full_assert.v15.0.7.x86_64-w64-mingw32-cxx11.tar.gz"
